openapi: 3.2.0
info:
  title: router Mcp Free API
  version: 0.1.0
tags:
- name: Mcp Free
paths:
  /mcp-free:
    post:
      summary: Mcp
      operationId: mcp_mcp_free_post
      parameters:
      - name: credits
        in: query
        required: false
        schema:
          type: integer
          default: 1
          title: Credits
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Mcp Free
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
